AR		:= ar
CC		:= $(CXX)
LD        	:= $(CXX)

MPI_INCDIR      = $(MPIHOME)/include
MPI_LIBDIR      = $(MPIHOME)/lib
HDF5_INCDIR	= $(HDF5HOME)/include
HDF5_LIBDIR	= $(HDF5HOME)/lib 
HDF5_LIB        = hdf5

PARMETIS_DIR	:= $(PARMETISHOME)
PARMETIS_INCDIR	:= $(PARMETIS_DIR)/include
PARMETIS_LIBDIR	:= $(PARMETIS_DIR)/lib

LINK_MPI        = -L$(MPI_LIBDIR) -lmpich

CFLAGS		= -Wall -I$(HDF5_INCDIR) -I$(MPI_INCDIR) -I../include
LDFLAGS		= -L$(HDF5_LIBDIR) 

include rules.make
