# This workflow will install Python dependencies, and build binary wheels for a variety of Python versions

name: "Binary wheels"

on:
  release:
    types: [published]
    
jobs:
  build-macos:
    runs-on: macOS-latest
    
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          export FC=gfortran
          export F77=gfortran
          brew install cmake hdf5-mpi
          python -m pip install --upgrade pip setuptools wheel cibuildwheel
          python -m pip install --upgrade numpy mpi4py h5py
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Build wheel
        run: |
          export PATH="/usr/local/opt/hdf5-parallel/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/hdf5-parallel/lib"
          export CPPFLAGS="-I/usr/local/opt/hdf5-parallel/include"
          export CC=mpicc
          export CXX=mpicxx
          python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update -y && sudo apt upgrade 
        sudo apt install build-essential cmake mpich libhdf5-mpich-dev 
        python -m pip install --upgrade pip setuptools wheel cibuildwheel
        python -m pip install --upgrade numpy mpi4py h5py
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist/
      env:
        CIBW_BUILD: cp37-* cp38-* cp39-*

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
