# This workflow will install Python dependencies, and build binary wheels for a variety of Python versions

name: "Binary wheels"

on:
  release:
    types: [published]
    
jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          echo "/usr/local/opt/hdf5-parallel/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.0
        env:
          LDFLAGS: -L/usr/local/opt/hdf5-parallel/lib
          CPPFLAGS: -I/usr/local/opt/hdf5-parallel/include
          FC: gfortran
          F77: gfortran
          CC: mpicc
          CXX: mpicxx
          CIBW_BUILD: cp37-* cp38-* cp39-*
          CIBW_BEFORE_BUILD: >
            brew install cmake pipx hdf5-mpi
        with:
          package-dir: .
          output-dir: dist

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
          
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt update -y && sudo apt upgrade 
        python -m pip install --upgrade pip setuptools wheel

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.10.0
      env:
        CIBW_BEFORE_BUILD: >
          apt update -y && apt upgrade &&
          apt install -y build-essential cmake mpich libhdf5-mpich-dev libpython3.7-dev libpython3.8-dev libpython3.9-dev
          
        CIBW_BUILD: cp37-* cp38-* cp39-*
        CIBW_ARCHS_LINUX: "auto64"
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
        CIBW_MANYLINUX_I686_IMAGE: manylinux_2_24
      with:
        package-dir: .
        output-dir: dist

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl
